// Code generated by protoc-gen-go.
// source: github.com/micro/micro/examples/template/srv/proto/example/example.proto
// DO NOT EDIT!

/*
Package go_micro_srv_template is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/micro/examples/template/srv/proto/example/example.proto

It has these top-level messages:
	Message
	Request
	Response
	StreamingRequest
	StreamingResponse
	Ping
	Pong
*/
package go_micro_srv_template

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say string `protobuf:"bytes,1,opt,name=say" json:"say,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StreamingRequest struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingRequest) Reset()                    { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()               {}
func (*StreamingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StreamingResponse struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingResponse) Reset()                    { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()               {}
func (*StreamingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Ping struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Pong struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.template.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.template.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.template.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.template.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.template.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.template.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.template.Pong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example service

type ExampleClient interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Example_StreamClient, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Example_PingPongClient, error)
}

type exampleClient struct {
	c           client.Client
	serviceName string
}

func NewExampleClient(serviceName string, c client.Client) ExampleClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.template"
	}
	return &exampleClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *exampleClient) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Example.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleClient) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Example_StreamClient, error) {
	req := c.c.NewRequest(c.serviceName, "Example.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &exampleStreamClient{stream}, nil
}

type Example_StreamClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type exampleStreamClient struct {
	stream client.Streamer
}

func (x *exampleStreamClient) Close() error {
	return x.stream.Close()
}

func (x *exampleStreamClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exampleStreamClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exampleStreamClient) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *exampleClient) PingPong(ctx context.Context, opts ...client.CallOption) (Example_PingPongClient, error) {
	req := c.c.NewRequest(c.serviceName, "Example.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &examplePingPongClient{stream}, nil
}

type Example_PingPongClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type examplePingPongClient struct {
	stream client.Streamer
}

func (x *examplePingPongClient) Close() error {
	return x.stream.Close()
}

func (x *examplePingPongClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *examplePingPongClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *examplePingPongClient) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *examplePingPongClient) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Example service

type ExampleHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Example_StreamStream) error
	PingPong(context.Context, Example_PingPongStream) error
}

func RegisterExampleHandler(s server.Server, hdlr ExampleHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Example{hdlr}, opts...))
}

type Example struct {
	ExampleHandler
}

func (h *Example) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ExampleHandler.Call(ctx, in, out)
}

func (h *Example) Stream(ctx context.Context, stream server.Streamer) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ExampleHandler.Stream(ctx, m, &exampleStreamStream{stream})
}

type Example_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type exampleStreamStream struct {
	stream server.Streamer
}

func (x *exampleStreamStream) Close() error {
	return x.stream.Close()
}

func (x *exampleStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *exampleStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *exampleStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *Example) PingPong(ctx context.Context, stream server.Streamer) error {
	return h.ExampleHandler.PingPong(ctx, &examplePingPongStream{stream})
}

type Example_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type examplePingPongStream struct {
	stream server.Streamer
}

func (x *examplePingPongStream) Close() error {
	return x.stream.Close()
}

func (x *examplePingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *examplePingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *examplePingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *examplePingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

var fileDescriptor0 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xb7, 0x6e, 0x6d, 0xd7, 0x39, 0xad, 0x41, 0x45, 0xba, 0xba, 0x4a, 0x2e, 0xd6, 0x4b,
	0xba, 0xe8, 0x23, 0x88, 0xa0, 0x82, 0x20, 0xf5, 0x01, 0x24, 0x5b, 0x86, 0x5a, 0x6c, 0x9a, 0xda,
	0xa4, 0xa2, 0x47, 0xdf, 0xdc, 0x36, 0x4d, 0x45, 0x64, 0xc3, 0x5e, 0x3a, 0x33, 0xfd, 0xbf, 0x7f,
	0x98, 0x19, 0x02, 0x77, 0x79, 0xa1, 0x5f, 0xdb, 0x35, 0xcb, 0xa4, 0x48, 0x44, 0x91, 0x35, 0xd2,
	0x7e, 0xf1, 0x93, 0x8b, 0xba, 0x44, 0x95, 0x68, 0xec, 0x22, 0xd7, 0x98, 0xa8, 0xe6, 0x23, 0xa9,
	0x1b, 0xa9, 0x7f, 0xb5, 0x31, 0x32, 0xf3, 0x97, 0x1c, 0xe6, 0x92, 0x19, 0x2f, 0xeb, 0x48, 0x36,
	0xda, 0xe8, 0x02, 0xc2, 0x47, 0x54, 0x8a, 0xe7, 0x48, 0xe6, 0x30, 0x55, 0xfc, 0xeb, 0xd8, 0x3b,
	0xf7, 0xe2, 0xbd, 0xb4, 0x4f, 0xe9, 0x29, 0x84, 0x29, 0xbe, 0xb7, 0xa8, 0x34, 0x21, 0xe0, 0x57,
	0x5c, 0xa0, 0x55, 0x4d, 0x4e, 0x4f, 0x60, 0x96, 0xa2, 0xaa, 0x65, 0xa5, 0x8c, 0x59, 0xa8, 0x7c,
	0x34, 0x77, 0x29, 0x8d, 0x61, 0xfe, 0xac, 0x1b, 0xe4, 0xa2, 0xa8, 0xf2, 0xb1, 0xcb, 0x01, 0xec,
	0x66, 0xb2, 0xad, 0xb4, 0xe1, 0xa6, 0xe9, 0x50, 0xd0, 0x4b, 0xd8, 0xff, 0x43, 0xda, 0x86, 0x9b,
	0xd1, 0x25, 0xf8, 0x4f, 0x1d, 0x45, 0x8e, 0x20, 0x50, 0xba, 0x91, 0x6f, 0x68, 0x65, 0x5b, 0x19,
	0x5d, 0xba, 0xf5, 0xab, 0xef, 0x1d, 0x08, 0x6f, 0x87, 0xbb, 0x90, 0x7b, 0xf0, 0x6f, 0x78, 0x59,
	0x92, 0x25, 0xdb, 0x78, 0x1a, 0x66, 0x87, 0x8e, 0xce, 0x9c, 0xfa, 0x30, 0x2a, 0x9d, 0x90, 0x17,
	0x08, 0x86, 0x0d, 0xc8, 0x85, 0x03, 0xfe, 0x7f, 0x8a, 0x28, 0xde, 0x0e, 0x8e, 0xed, 0x57, 0x1e,
	0x79, 0x80, 0x59, 0xbf, 0xb7, 0xd9, 0x6d, 0xe1, 0x70, 0xf6, 0x40, 0xe4, 0x14, 0x3b, 0x27, 0x9d,
	0xc4, 0xde, 0xca, 0x5b, 0x07, 0xe6, 0x41, 0x5c, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x93,
	0xe9, 0x38, 0x5c, 0x02, 0x00, 0x00,
}
