// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debug.proto

package go_micro_debug_stats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Service describes a service running in the micro network.
type Service struct {
	// Service name, e.g. go.micro.service.greeter
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Node                 *Node    `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{0}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Service) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

// Node describes a single instance of a service.
type Node struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{1}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Snapshot is a snapshot of Debug.Stats from a particular service when called.
type Snapshot struct {
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// Unix timestamp, e.g. 1575561487
	Started int64 `protobuf:"varint,2,opt,name=started,proto3" json:"started,omitempty"`
	// Uptime in seconds
	Uptime uint64 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Heap allocated in bytes (TODO: change to resident set size)
	Memory uint64 `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	// Number of Goroutines
	Threads uint64 `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	// GC Pause total in ns
	Gc                   uint64   `protobuf:"varint,6,opt,name=gc,proto3" json:"gc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{2}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *Snapshot) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Snapshot) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *Snapshot) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Snapshot) GetThreads() uint64 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *Snapshot) GetGc() uint64 {
	if m != nil {
		return m.Gc
	}
	return 0
}

type ReadRequest struct {
	// If set, only return services matching the filter
	Filter *Service `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// If set, only return services matching the namespace
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{3}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetFilter() *Service {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ReadRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ReadResponse struct {
	Stats                []*Snapshot `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{4}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetStats() []*Snapshot {
	if m != nil {
		return m.Stats
	}
	return nil
}

type StreamRequest struct {
	// If set, only return services matching the filter
	Service *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// If set, only return services matching the namespace
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{5}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *StreamRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type StreamResponse struct {
	Stats                []*Snapshot `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d9d361be58531fb, []int{6}
}

func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (m *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(m, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetStats() []*Snapshot {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "go.micro.debug.stats.Service")
	proto.RegisterType((*Node)(nil), "go.micro.debug.stats.Node")
	proto.RegisterType((*Snapshot)(nil), "go.micro.debug.stats.Snapshot")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.debug.stats.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.debug.stats.ReadResponse")
	proto.RegisterType((*StreamRequest)(nil), "go.micro.debug.stats.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "go.micro.debug.stats.StreamResponse")
}

func init() { proto.RegisterFile("debug.proto", fileDescriptor_8d9d361be58531fb) }

var fileDescriptor_8d9d361be58531fb = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0x86, 0x91, 0x2c, 0xcb, 0xf5, 0xa8, 0xf5, 0x61, 0x29, 0x66, 0x31, 0x6d, 0x71, 0xd5, 0x1e,
	0x7c, 0x12, 0x45, 0x4d, 0xc8, 0x0b, 0x84, 0xdc, 0x92, 0xc3, 0x8a, 0x3c, 0xc0, 0x5a, 0x3b, 0x96,
	0x05, 0x91, 0x56, 0xd9, 0x5d, 0x1b, 0xf2, 0x50, 0x39, 0xe7, 0xf5, 0xc2, 0xee, 0x4a, 0xc4, 0x07,
	0xdb, 0x84, 0xe4, 0x36, 0xff, 0xaf, 0x5f, 0x33, 0x9f, 0x7e, 0x10, 0x24, 0x02, 0xd7, 0xbb, 0x2a,
	0xeb, 0x94, 0x34, 0x92, 0x7c, 0xaf, 0x64, 0xd6, 0xd4, 0xa5, 0x92, 0x99, 0x77, 0xb5, 0xe1, 0x46,
	0xa7, 0x15, 0x4c, 0x0a, 0x54, 0xfb, 0xba, 0x44, 0x42, 0x20, 0x6a, 0x79, 0x83, 0x34, 0x58, 0x06,
	0xab, 0x29, 0x73, 0x33, 0xa1, 0x30, 0xd9, 0xa3, 0xd2, 0xb5, 0x6c, 0x69, 0xe8, 0xec, 0x41, 0x92,
	0x0c, 0xa2, 0x56, 0x0a, 0xa4, 0xa3, 0x65, 0xb0, 0x4a, 0xf2, 0x45, 0x76, 0x6c, 0x7b, 0x76, 0x27,
	0x05, 0x32, 0x97, 0x4b, 0xe7, 0x10, 0x59, 0x45, 0x66, 0x10, 0xd6, 0xa2, 0xbf, 0x11, 0xd6, 0x22,
	0x7d, 0x09, 0xe0, 0x4b, 0xd1, 0xf2, 0x4e, 0x6f, 0xa5, 0x21, 0x57, 0x30, 0xd1, 0x9e, 0xc6, 0x25,
	0x92, 0xfc, 0xe7, 0xf1, 0xbd, 0x3d, 0x32, 0x1b, 0xd2, 0x96, 0x53, 0x1b, 0xae, 0x0c, 0x0a, 0xc7,
	0x39, 0x62, 0x83, 0x24, 0x73, 0x88, 0x77, 0x9d, 0xa9, 0x1b, 0x4f, 0x1a, 0xb1, 0x5e, 0x59, 0xbf,
	0xc1, 0x46, 0xaa, 0x27, 0x1a, 0x79, 0xdf, 0x2b, 0xbb, 0xc9, 0x6c, 0x15, 0x72, 0xa1, 0xe9, 0xd8,
	0x3d, 0x18, 0xa4, 0x25, 0xaf, 0x4a, 0x1a, 0x3b, 0x33, 0xac, 0xca, 0x74, 0x0d, 0x09, 0x43, 0x2e,
	0x18, 0x3e, 0xee, 0x50, 0x1b, 0x72, 0x09, 0xf1, 0xa6, 0x7e, 0x30, 0xa8, 0xde, 0x87, 0xde, 0x87,
	0xc9, 0x0f, 0x98, 0xda, 0xa6, 0x75, 0xc7, 0x4b, 0xec, 0x3b, 0x7e, 0x33, 0xd2, 0x6b, 0xf8, 0xea,
	0x6f, 0xe8, 0x4e, 0xb6, 0x1a, 0xc9, 0x05, 0x8c, 0xdd, 0x1a, 0x1a, 0x2c, 0x47, 0xab, 0x24, 0xff,
	0x75, 0xe2, 0x46, 0xdf, 0x27, 0xf3, 0xe1, 0x74, 0x03, 0xdf, 0x0a, 0xa3, 0x90, 0x37, 0x03, 0xeb,
	0x87, 0x7b, 0x3e, 0x4f, 0x7b, 0x03, 0xb3, 0xe1, 0xce, 0x67, 0x78, 0xf3, 0xe7, 0x00, 0xc6, 0x85,
	0x9d, 0xc8, 0x2d, 0x44, 0xf6, 0xfb, 0xc9, 0xef, 0xe3, 0x2f, 0x1e, 0xf4, 0xbf, 0x48, 0xcf, 0x45,
	0x7a, 0x9c, 0x7b, 0x88, 0x3d, 0x20, 0xf9, 0x73, 0x82, 0xe4, 0xb0, 0xa6, 0xc5, 0xdf, 0xf3, 0x21,
	0xbf, 0xf4, 0x5f, 0xb0, 0x8e, 0xdd, 0x1f, 0xf6, 0xff, 0x35, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x7d,
	0x7e, 0xf0, 0x70, 0x03, 0x00, 0x00,
}
