# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: config/config.proto for package 'config'

require 'grpc'
require 'config/config_pb'

module Config
  module Config
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'config.Config'

      rpc :Get, ::Config::GetRequest, ::Config::GetResponse
      rpc :Set, ::Config::SetRequest, ::Config::SetResponse
      rpc :Delete, ::Config::DeleteRequest, ::Config::DeleteResponse
      # These methods are here for backwards compatibility reasons
      rpc :Read, ::Config::ReadRequest, ::Config::ReadResponse
    end

    Stub = Service.rpc_stub_class
  end
end
