FROM netdata/netdata:latest-amd64

COPY --chown=root:netdata collector /usr/libexec/netdata/plugins.d/micro.d.plugin
RUN chown root:netdata /usr/libexec/netdata/plugins.d/micro.d.plugin
RUN chmod 0750 /usr/libexec/netdata/plugins.d/micro.d.plugin
