# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api/api.proto for package 'api'

require 'grpc'
require 'api/api_pb'

module Api
  module Api
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'api.Api'

      rpc :Register, ::Api::Endpoint, ::Api::EmptyResponse
      rpc :Deregister, ::Api::Endpoint, ::Api::EmptyResponse
    end

    Stub = Service.rpc_stub_class
  end
end
