// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/store/proto/store.proto

package store

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Field struct {
	// type of value e.g string, int, int64, bool, float64
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// the actual value
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{0}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Record struct {
	// key of the record
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value in the record
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// time.Duration (signed int64 nanoseconds)
	Expiry int64 `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// the associated metadata
	Metadata             map[string]*Field `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Record) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Record) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *Record) GetMetadata() map[string]*Field {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReadOptions struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Prefix               bool     `protobuf:"varint,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               bool     `protobuf:"varint,4,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Limit                uint64   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOptions) Reset()         { *m = ReadOptions{} }
func (m *ReadOptions) String() string { return proto.CompactTextString(m) }
func (*ReadOptions) ProtoMessage()    {}
func (*ReadOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{2}
}

func (m *ReadOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOptions.Unmarshal(m, b)
}
func (m *ReadOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOptions.Marshal(b, m, deterministic)
}
func (m *ReadOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOptions.Merge(m, src)
}
func (m *ReadOptions) XXX_Size() int {
	return xxx_messageInfo_ReadOptions.Size(m)
}
func (m *ReadOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOptions proto.InternalMessageInfo

func (m *ReadOptions) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ReadOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ReadOptions) GetPrefix() bool {
	if m != nil {
		return m.Prefix
	}
	return false
}

func (m *ReadOptions) GetSuffix() bool {
	if m != nil {
		return m.Suffix
	}
	return false
}

func (m *ReadOptions) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadOptions) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ReadRequest struct {
	Key                  string       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Options              *ReadOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{3}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReadRequest) GetOptions() *ReadOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type ReadResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{4}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

type WriteOptions struct {
	Database string `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table    string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	// time.Time
	Expiry int64 `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	// time.Duration
	Ttl                  int64    `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteOptions) Reset()         { *m = WriteOptions{} }
func (m *WriteOptions) String() string { return proto.CompactTextString(m) }
func (*WriteOptions) ProtoMessage()    {}
func (*WriteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{5}
}

func (m *WriteOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteOptions.Unmarshal(m, b)
}
func (m *WriteOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteOptions.Marshal(b, m, deterministic)
}
func (m *WriteOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteOptions.Merge(m, src)
}
func (m *WriteOptions) XXX_Size() int {
	return xxx_messageInfo_WriteOptions.Size(m)
}
func (m *WriteOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WriteOptions proto.InternalMessageInfo

func (m *WriteOptions) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *WriteOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *WriteOptions) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *WriteOptions) GetTtl() int64 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type WriteRequest struct {
	Record               *Record       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	Options              *WriteOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{6}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

func (m *WriteRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *WriteRequest) GetOptions() *WriteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type WriteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{7}
}

func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (m *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(m, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

type DeleteOptions struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOptions) Reset()         { *m = DeleteOptions{} }
func (m *DeleteOptions) String() string { return proto.CompactTextString(m) }
func (*DeleteOptions) ProtoMessage()    {}
func (*DeleteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{8}
}

func (m *DeleteOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOptions.Unmarshal(m, b)
}
func (m *DeleteOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOptions.Marshal(b, m, deterministic)
}
func (m *DeleteOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOptions.Merge(m, src)
}
func (m *DeleteOptions) XXX_Size() int {
	return xxx_messageInfo_DeleteOptions.Size(m)
}
func (m *DeleteOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOptions proto.InternalMessageInfo

func (m *DeleteOptions) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *DeleteOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type DeleteRequest struct {
	Key                  string         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Options              *DeleteOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteRequest) GetOptions() *DeleteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

type ListOptions struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Prefix               string   `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix               string   `protobuf:"bytes,4,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Limit                uint64   `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint64   `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOptions) Reset()         { *m = ListOptions{} }
func (m *ListOptions) String() string { return proto.CompactTextString(m) }
func (*ListOptions) ProtoMessage()    {}
func (*ListOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{11}
}

func (m *ListOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOptions.Unmarshal(m, b)
}
func (m *ListOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOptions.Marshal(b, m, deterministic)
}
func (m *ListOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOptions.Merge(m, src)
}
func (m *ListOptions) XXX_Size() int {
	return xxx_messageInfo_ListOptions.Size(m)
}
func (m *ListOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ListOptions proto.InternalMessageInfo

func (m *ListOptions) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ListOptions) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ListOptions) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *ListOptions) GetSuffix() string {
	if m != nil {
		return m.Suffix
	}
	return ""
}

func (m *ListOptions) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOptions) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ListRequest struct {
	Options              *ListOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{12}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOptions() *ListOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type ListResponse struct {
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{13}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type DatabasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabasesRequest) Reset()         { *m = DatabasesRequest{} }
func (m *DatabasesRequest) String() string { return proto.CompactTextString(m) }
func (*DatabasesRequest) ProtoMessage()    {}
func (*DatabasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{14}
}

func (m *DatabasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabasesRequest.Unmarshal(m, b)
}
func (m *DatabasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabasesRequest.Marshal(b, m, deterministic)
}
func (m *DatabasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabasesRequest.Merge(m, src)
}
func (m *DatabasesRequest) XXX_Size() int {
	return xxx_messageInfo_DatabasesRequest.Size(m)
}
func (m *DatabasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DatabasesRequest proto.InternalMessageInfo

type DatabasesResponse struct {
	Databases            []string `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatabasesResponse) Reset()         { *m = DatabasesResponse{} }
func (m *DatabasesResponse) String() string { return proto.CompactTextString(m) }
func (*DatabasesResponse) ProtoMessage()    {}
func (*DatabasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{15}
}

func (m *DatabasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatabasesResponse.Unmarshal(m, b)
}
func (m *DatabasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatabasesResponse.Marshal(b, m, deterministic)
}
func (m *DatabasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatabasesResponse.Merge(m, src)
}
func (m *DatabasesResponse) XXX_Size() int {
	return xxx_messageInfo_DatabasesResponse.Size(m)
}
func (m *DatabasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DatabasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DatabasesResponse proto.InternalMessageInfo

func (m *DatabasesResponse) GetDatabases() []string {
	if m != nil {
		return m.Databases
	}
	return nil
}

type TablesRequest struct {
	Database             string   `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TablesRequest) Reset()         { *m = TablesRequest{} }
func (m *TablesRequest) String() string { return proto.CompactTextString(m) }
func (*TablesRequest) ProtoMessage()    {}
func (*TablesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{16}
}

func (m *TablesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TablesRequest.Unmarshal(m, b)
}
func (m *TablesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TablesRequest.Marshal(b, m, deterministic)
}
func (m *TablesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TablesRequest.Merge(m, src)
}
func (m *TablesRequest) XXX_Size() int {
	return xxx_messageInfo_TablesRequest.Size(m)
}
func (m *TablesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TablesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TablesRequest proto.InternalMessageInfo

func (m *TablesRequest) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

type TablesResponse struct {
	Tables               []string `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TablesResponse) Reset()         { *m = TablesResponse{} }
func (m *TablesResponse) String() string { return proto.CompactTextString(m) }
func (*TablesResponse) ProtoMessage()    {}
func (*TablesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3b1a2f06b010ee4, []int{17}
}

func (m *TablesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TablesResponse.Unmarshal(m, b)
}
func (m *TablesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TablesResponse.Marshal(b, m, deterministic)
}
func (m *TablesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TablesResponse.Merge(m, src)
}
func (m *TablesResponse) XXX_Size() int {
	return xxx_messageInfo_TablesResponse.Size(m)
}
func (m *TablesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TablesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TablesResponse proto.InternalMessageInfo

func (m *TablesResponse) GetTables() []string {
	if m != nil {
		return m.Tables
	}
	return nil
}

func init() {
	proto.RegisterType((*Field)(nil), "go.micro.store.Field")
	proto.RegisterType((*Record)(nil), "go.micro.store.Record")
	proto.RegisterMapType((map[string]*Field)(nil), "go.micro.store.Record.MetadataEntry")
	proto.RegisterType((*ReadOptions)(nil), "go.micro.store.ReadOptions")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.store.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.store.ReadResponse")
	proto.RegisterType((*WriteOptions)(nil), "go.micro.store.WriteOptions")
	proto.RegisterType((*WriteRequest)(nil), "go.micro.store.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "go.micro.store.WriteResponse")
	proto.RegisterType((*DeleteOptions)(nil), "go.micro.store.DeleteOptions")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.store.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.store.DeleteResponse")
	proto.RegisterType((*ListOptions)(nil), "go.micro.store.ListOptions")
	proto.RegisterType((*ListRequest)(nil), "go.micro.store.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.store.ListResponse")
	proto.RegisterType((*DatabasesRequest)(nil), "go.micro.store.DatabasesRequest")
	proto.RegisterType((*DatabasesResponse)(nil), "go.micro.store.DatabasesResponse")
	proto.RegisterType((*TablesRequest)(nil), "go.micro.store.TablesRequest")
	proto.RegisterType((*TablesResponse)(nil), "go.micro.store.TablesResponse")
}

func init() { proto.RegisterFile("service/store/proto/store.proto", fileDescriptor_e3b1a2f06b010ee4) }

var fileDescriptor_e3b1a2f06b010ee4 = []byte{
	// 681 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0x6b, 0xc7, 0x4d, 0xa6, 0x49, 0xbf, 0x7c, 0x2b, 0xa8, 0xac, 0xd0, 0x42, 0x58, 0x71,
	0x11, 0xa9, 0x92, 0xd3, 0x1f, 0x15, 0x10, 0xdc, 0x14, 0x68, 0x2b, 0x81, 0x40, 0x48, 0x0b, 0x02,
	0xa9, 0x77, 0x4e, 0xb2, 0x29, 0xa6, 0x49, 0x6d, 0xbc, 0x9b, 0xa8, 0x79, 0x18, 0x1e, 0x87, 0xd7,
	0xe0, 0x59, 0xd0, 0xfe, 0x39, 0xb6, 0x63, 0xf7, 0x82, 0x72, 0x53, 0xed, 0xcc, 0xce, 0x9e, 0x39,
	0xe7, 0xcc, 0xb8, 0x81, 0x47, 0x8c, 0x26, 0xf3, 0x70, 0x48, 0xfb, 0x8c, 0x47, 0x09, 0xed, 0xc7,
	0x49, 0xc4, 0x23, 0x75, 0xf6, 0xe5, 0x19, 0x6d, 0x5d, 0x46, 0xfe, 0x34, 0x1c, 0x26, 0x91, 0x2f,
	0xb3, 0xf8, 0x00, 0x6a, 0xe7, 0x21, 0x9d, 0x8c, 0x10, 0x02, 0x87, 0x2f, 0x62, 0xea, 0x59, 0x5d,
	0xab, 0xd7, 0x20, 0xf2, 0x8c, 0xee, 0x41, 0x6d, 0x1e, 0x4c, 0x66, 0xd4, 0x5b, 0x97, 0x49, 0x15,
	0xe0, 0xdf, 0x16, 0xb8, 0x84, 0x0e, 0xa3, 0x64, 0x84, 0xda, 0x60, 0x5f, 0xd1, 0x85, 0x7e, 0x23,
	0x8e, 0xf9, 0x27, 0x4d, 0xfd, 0x04, 0x6d, 0x83, 0x4b, 0x6f, 0xe2, 0x30, 0x59, 0x78, 0x76, 0xd7,
	0xea, 0xd9, 0x44, 0x47, 0xe8, 0x04, 0xea, 0x53, 0xca, 0x83, 0x51, 0xc0, 0x03, 0xcf, 0xe9, 0xda,
	0xbd, 0xcd, 0xc3, 0x27, 0x7e, 0x9e, 0xa0, 0xaf, 0x3a, 0xf9, 0x1f, 0x74, 0xd9, 0xd9, 0x35, 0x4f,
	0x16, 0x24, 0x7d, 0xd5, 0x21, 0xd0, 0xca, 0x5d, 0x95, 0x50, 0xda, 0xcb, 0x52, 0xda, 0x3c, 0xbc,
	0x5f, 0xec, 0x20, 0xf5, 0x6b, 0xa6, 0x2f, 0xd6, 0x9f, 0x5b, 0xf8, 0xa7, 0x05, 0x9b, 0x84, 0x06,
	0xa3, 0x8f, 0x31, 0x0f, 0xa3, 0x6b, 0x86, 0x3a, 0x50, 0x17, 0xf8, 0x83, 0x80, 0x19, 0x7b, 0xd2,
	0x58, 0xe8, 0xe5, 0xc1, 0x60, 0x92, 0x5a, 0x24, 0x03, 0xa1, 0x37, 0x4e, 0xe8, 0x38, 0xbc, 0x91,
	0x7a, 0xeb, 0x44, 0x47, 0x22, 0xcf, 0x66, 0x63, 0x91, 0x77, 0x54, 0x5e, 0x45, 0x02, 0x65, 0x12,
	0x4e, 0x43, 0xee, 0xd5, 0xba, 0x56, 0xcf, 0x21, 0x2a, 0x10, 0xd5, 0xd1, 0x78, 0xcc, 0x28, 0xf7,
	0x5c, 0x99, 0xd6, 0x11, 0xfe, 0xa2, 0xe8, 0x11, 0xfa, 0x63, 0x46, 0x19, 0x2f, 0x51, 0x7c, 0x0c,
	0x1b, 0x91, 0xe2, 0xae, 0x35, 0x3f, 0x58, 0x75, 0x35, 0x95, 0x47, 0x4c, 0x2d, 0x3e, 0x81, 0xa6,
	0xc2, 0x65, 0x71, 0x74, 0xcd, 0x28, 0xda, 0x87, 0x8d, 0x44, 0xba, 0xcf, 0x3c, 0x4b, 0x0e, 0x67,
	0xbb, 0x7c, 0x38, 0xc4, 0x94, 0xe1, 0xef, 0xd0, 0xfc, 0x9a, 0x84, 0x9c, 0xde, 0xc9, 0xb9, 0xd2,
	0x4d, 0x69, 0x83, 0xcd, 0xf9, 0x44, 0xda, 0x66, 0x13, 0x71, 0xc4, 0x73, 0xdd, 0xcb, 0xd8, 0xe0,
	0x83, 0xab, 0x68, 0xc8, 0x4e, 0xd5, 0x64, 0x75, 0x15, 0x7a, 0x5a, 0x34, 0x69, 0xa7, 0xf8, 0x20,
	0x2b, 0x65, 0xe9, 0xd2, 0x7f, 0xd0, 0xd2, 0x7d, 0x95, 0x4d, 0xf8, 0x15, 0xb4, 0x4e, 0xe9, 0x84,
	0xde, 0x41, 0x35, 0xbe, 0x30, 0x10, 0xd5, 0x33, 0x7d, 0x56, 0xa4, 0xbb, 0x5b, 0xa4, 0x9b, 0x23,
	0xb1, 0xe4, 0xdb, 0x86, 0x2d, 0x83, 0xad, 0x09, 0x8b, 0xfd, 0x7e, 0x1f, 0x32, 0xfe, 0xaf, 0xf6,
	0xbb, 0x51, 0xb1, 0xdf, 0x8d, 0xbf, 0xdc, 0xef, 0x53, 0x45, 0xcf, 0x78, 0x91, 0xd9, 0x66, 0xab,
	0x7c, 0x9b, 0x33, 0x62, 0x96, 0xba, 0x7b, 0xd0, 0x54, 0x28, 0x7a, 0x9b, 0x11, 0x38, 0x57, 0x74,
	0x21, 0xdc, 0xb3, 0xc5, 0x3f, 0x38, 0x71, 0x7e, 0xe7, 0xd4, 0xad, 0xf6, 0x3a, 0x46, 0xd0, 0x3e,
	0xd5, 0x7a, 0x99, 0x6e, 0x8a, 0x0f, 0xe0, 0xff, 0x4c, 0x4e, 0x43, 0xec, 0x40, 0xc3, 0x18, 0xa3,
	0x3e, 0x89, 0x06, 0x59, 0x26, 0xf0, 0x1e, 0xb4, 0x3e, 0x0b, 0x77, 0x0c, 0xc6, 0x6d, 0xbe, 0xe2,
	0x1e, 0x6c, 0x99, 0x62, 0x0d, 0xbe, 0x0d, 0xae, 0x34, 0xd7, 0x20, 0xeb, 0xe8, 0xf0, 0x97, 0x0d,
	0xb5, 0x4f, 0x42, 0x26, 0x7a, 0x03, 0x8e, 0xf8, 0x3e, 0x51, 0xe9, 0xd7, 0xac, 0x9b, 0x76, 0x76,
	0xca, 0x2f, 0xf5, 0xe8, 0xd7, 0xd0, 0x39, 0xd4, 0xe4, 0xfa, 0xa2, 0xf2, 0x75, 0x37, 0x30, 0xbb,
	0x15, 0xb7, 0x29, 0xce, 0x5b, 0x70, 0xd5, 0x5a, 0xa1, 0x8a, 0x45, 0x34, 0x48, 0x0f, 0xab, 0xae,
	0x53, 0xa8, 0x33, 0x70, 0xc4, 0xa4, 0x50, 0xe9, 0x5c, 0x2b, 0x75, 0x65, 0x87, 0x8b, 0xd7, 0xf6,
	0x2d, 0x44, 0xa0, 0x91, 0x8e, 0x0c, 0x75, 0x57, 0xba, 0x16, 0x26, 0xdc, 0x79, 0x7c, 0x4b, 0x45,
	0x56, 0xa5, 0x1a, 0xd3, 0xaa, 0xca, 0xdc, 0xac, 0x57, 0x55, 0xe6, 0xa7, 0x8b, 0xd7, 0x5e, 0x1f,
	0x5f, 0x1c, 0x5d, 0x86, 0xfc, 0xdb, 0x6c, 0xe0, 0x0f, 0xa3, 0x69, 0x5f, 0x96, 0xea, 0xbf, 0xf3,
	0xa3, 0x7e, 0xc9, 0xcf, 0xf6, 0x4b, 0x79, 0x1e, 0xb8, 0x32, 0x38, 0xfa, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0x2b, 0x87, 0x1f, 0xda, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (Store_ListClient, error)
	Databases(ctx context.Context, in *DatabasesRequest, opts ...grpc.CallOption) (*DatabasesResponse, error)
	Tables(ctx context.Context, in *TablesRequest, opts ...grpc.CallOption) (*TablesResponse, error)
}

type storeClient struct {
	cc *grpc.ClientConn
}

func NewStoreClient(cc *grpc.ClientConn) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/go.micro.store.Store/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, "/go.micro.store.Store/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/go.micro.store.Store/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (Store_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Store_serviceDesc.Streams[0], "/go.micro.store.Store/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Store_ListClient interface {
	Recv() (*ListResponse, error)
	grpc.ClientStream
}

type storeListClient struct {
	grpc.ClientStream
}

func (x *storeListClient) Recv() (*ListResponse, error) {
	m := new(ListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeClient) Databases(ctx context.Context, in *DatabasesRequest, opts ...grpc.CallOption) (*DatabasesResponse, error) {
	out := new(DatabasesResponse)
	err := c.cc.Invoke(ctx, "/go.micro.store.Store/Databases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) Tables(ctx context.Context, in *TablesRequest, opts ...grpc.CallOption) (*TablesResponse, error) {
	out := new(TablesResponse)
	err := c.cc.Invoke(ctx, "/go.micro.store.Store/Tables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	List(*ListRequest, Store_ListServer) error
	Databases(context.Context, *DatabasesRequest) (*DatabasesResponse, error)
	Tables(context.Context, *TablesRequest) (*TablesResponse, error)
}

// UnimplementedStoreServer can be embedded to have forward compatible implementations.
type UnimplementedStoreServer struct {
}

func (*UnimplementedStoreServer) Read(ctx context.Context, req *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedStoreServer) Write(ctx context.Context, req *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (*UnimplementedStoreServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedStoreServer) List(req *ListRequest, srv Store_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedStoreServer) Databases(ctx context.Context, req *DatabasesRequest) (*DatabasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Databases not implemented")
}
func (*UnimplementedStoreServer) Tables(ctx context.Context, req *TablesRequest) (*TablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tables not implemented")
}

func RegisterStoreServer(s *grpc.Server, srv StoreServer) {
	s.RegisterService(&_Store_serviceDesc, srv)
}

func _Store_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.store.Store/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.store.Store/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.store.Store/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServer).List(m, &storeListServer{stream})
}

type Store_ListServer interface {
	Send(*ListResponse) error
	grpc.ServerStream
}

type storeListServer struct {
	grpc.ServerStream
}

func (x *storeListServer) Send(m *ListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Store_Databases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Databases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.store.Store/Databases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Databases(ctx, req.(*DatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_Tables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).Tables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.store.Store/Tables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).Tables(ctx, req.(*TablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Store_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.store.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Store_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Store_Write_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Store_Delete_Handler,
		},
		{
			MethodName: "Databases",
			Handler:    _Store_Databases_Handler,
		},
		{
			MethodName: "Tables",
			Handler:    _Store_Tables_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Store_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service/store/proto/store.proto",
}
