export const SET_REGISTRY_SERVICES = "SET_REGISTRY_SERVICES";
export const SET_WEB_SERVICES = "SET_WEB_SERVICES";
export const SET_REGISTRY_TABLE_LOADING = "SET_REGISTRY_TABLE_LOADING";
export const SET_REGISTRY_SERVICE_DETAIL = "SET_REGISTRY_SERVICE_DETAIL";
export const SET_REGISTRY_SERVICE_DETAIL_LOADING = "SET_REGISTRY_SERVICE_DETAIL_LOADING";


export const SET_CALL_SERVICES = "SET_CALL_SERVICES";
export const SET_CALL_LOADING = "SET_CALL_LOADING";
export const SET_CALL_RESULT = "SET_CALL_RESULT";


export const SET_SERVICES_STATS_SERVICES = "SET_SERVICES_STATS_SERVICES";
export const SET_SERVICES_STATS_PAGE_LOADING = "SET_SERVICES_STATS_PAGE_LOADING";
export const SET_SERVICES_STATS_NODE_STATS = "SET_SERVICES_STATS_NODE_STATS";
export const SET_SERVICES_STATS_DATA_LOADING = "SET_SERVICES_STATS_DATA_LOADING";
export const SET_SERVICES_STATS_DATA_ERROR = "SET_SERVICES_STATS_DATA_ERROR";

export const SET_API_STATS_SERVICES = "SET_API_STATS_SERVICES";
export const SET_API_STATS_NODE_STATS = "SET_API_STATS_NODE_STATS";
export const SET_API_STATS_DATA_LOADING = "SET_API_STATS_DATA_LOADING";
export const SET_API_STATS_DATA_ERROR = "SET_API_STATS_DATA_ERROR";
