export const SET_REGISTRY_SERVICES = "SET_REGISTRY_SERVICES";
export const SET_REGISTRY_TABLE_LOADING = "SET_REGISTRY_TABLE_LOADING";
export const SET_REGISTRY_SERVICE_DETAIL = "SET_REGISTRY_SERVICE_DETAIL";
export const SET_REGISTRY_SERVICE_DETAIL_LOADING = "SET_REGISTRY_SERVICE_DETAIL_LOADING";